In [2]:
import pandas as pd     
orders=pd.Series(["Delivered","Cancelled","Delivered","Pending"])
print(orders.dtype)
orders=orders.astype("category")
print(orders.dtype)

object
category


In [3]:
import pandas as pd
salary=[1000,2000,3000,4000]
new_salary=[]
for s in salary:
    new_salary.append(s*1.1)
print(new_salary)

[1100.0, 2200.0, 3300.0000000000005, 4400.0]


In [5]:
import numpy as np
salary=np.array([1000,2000,3000,4000,5000])
new_salary=salary*1.1
print(new_salary)

[1100. 2200. 3300. 4400. 5500.]


In [6]:
import numpy as np 
prize=np.array([1200,1300,1400,1500])
discount=prize*0.5
print(discount)

[600. 650. 700. 750.]


In [3]:
import pandas as pd
data=pd.Series(range(1,10))
sample=data.sample(5)
print(sample)

0    1
8    9
4    5
1    2
6    7
dtype: int64


In [5]:
sample=data.sample(frac=0.2)
print(sample)

5    6
7    8
dtype: int64


In [3]:
import numpy as np
salary=([50000,65000,34000,5600])
print(np.median(salary))

42000.0


In [5]:
import numpy as np
salary=([23000,34000,67000,89000])
print(np.mean(salary))

53250.0


In [8]:
from scipy import stats
data=[10,20,30,40,50,60,60]
print(stats.mode(data))

ModeResult(mode=np.int64(60), count=np.int64(2))


In [9]:
import numpy as np
salary=([2500,3400,5600,5400])
print(np.max(salary))

5600


In [10]:
salary=([2500,3400,5600,5400])
print(np.min(salary))

2500


In [11]:
salary=([2500,3400,5600,5400])
print(np.max(salary)-min(salary))

3100


In [12]:
salary=([10,20,30,40,50])
print(np.var(salary))

200.0


In [13]:
salary=([200,300,400,500,600])
print(np.std(salary))

141.4213562373095


In [15]:
marks=([10,34,20,40,50,60])
print(np.min(marks))
print(np.max(marks))
print(np.max(marks)-min(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.var(marks))
print(np.std(marks))

10
60
50
35.666666666666664
37.0
287.2222222222222
16.94763175851488


In [17]:
import pandas as pd
student={
    "Name":["Ayubb","Ayan","Afrin"],
    "Marks":[100,95,80]
}
details=pd.DataFrame(student)
print(details.sample(2))
 

    Name  Marks
2  Afrin     80
1   Ayan     95


In [18]:
import pandas as pd 
student={
    "Name":["Varun","stya","soumii"],
    "Marks":[250,300,400]
}
details=pd.DataFrame(student)
details.sample(3,random_state=0)

,Name,Marks
2,soumii,400
1,stya,300
0,Varun,250


In [21]:
import numpy as np
salary=np.array([2300,4500,6007,3400])
bonus=salary+900
print(bonus)

[3200 5400 6907 4300]
