In [1]:
import numpy as np
num=[10,20,30,40]
arr=np.array([10,20,30,40])
print(arr)


[10 20 30 40]


In [2]:
flowers=["rose","lilly","jasmine"]
print(flowers)

['rose', 'lilly', 'jasmine']


In [3]:
arr=([[10,20],[30,40],[50,60]])
print(arr)

[[10, 20], [30, 40], [50, 60]]


In [5]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [6]:
a=np.array([200,300,400,500])
print(np.mean(a))
print(np.max(a))
print(np.max(a))
print(np.sum(a))
print(np.average(a))


350.0
500
500
1400
350.0


In [13]:
def count(x):
    if x == 0:
        return
    print(x)
    count(x-1)
n=int(input("enter a number:"))
count(n)

enter a number: 10


10
9
8
7
6
5
4
3
2
1


In [21]:
def count(n):
    if n == 0:
        return
    print("hello")
    count(n-1) 
n=int(input("enter a number: "))
count(n)

enter a number:  5


hello
hello
hello
hello
hello


In [24]:
def count(n):
    if n == 3:
        return
    print(n)
    count(n-1)
n=int(input("enter  a number: "))
count(5)

enter  a number:  18


5
4


In [26]:
def fact(n):
    if(n==1):
        return
        return n*fact(n-1)
n=int(input("enter a number: "))
count(5)

enter a number:  45


5
4
